environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g babel-cli eslint
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

init:
  - git config --global core.autocrlf true

build: false
